// RFQ Status
const RFQ_STATUS = {
  DRAFT: 'DRAFT',
  UPCOMING: 'UPCOMING',
  ACTIVE: 'ACTIVE',
  CLOSED: 'CLOSED',
  FORCE_CLOSED: 'FORCE_CLOSED',
  CANCELLED: 'CANCELLED'
};

// Trigger Types for Auction Extension
const TRIGGER_TYPE = {
  BID_RECEIVED: 'BID_RECEIVED',
  ANY_RANK_CHANGE: 'ANY_RANK_CHANGE',
  L1_CHANGE: 'L1_CHANGE'
};

// Action Types for Activity Logs
const ACTION_TYPE = {
  RFQ_CREATED: 'RFQ_CREATED',
  RFQ_UPDATED: 'RFQ_UPDATED',
  RFQ_CANCELLED: 'RFQ_CANCELLED',
  BID_SUBMITTED: 'BID_SUBMITTED',
  BID_REJECTED: 'BID_REJECTED',
  RANK_CHANGED: 'RANK_CHANGED',
  L1_CHANGED: 'L1_CHANGED',
  AUCTION_EXTENDED: 'AUCTION_EXTENDED',
  AUCTION_CLOSED: 'AUCTION_CLOSED',
  AUCTION_FORCE_CLOSED: 'AUCTION_FORCE_CLOSED',
  WINNER_SELECTED: 'WINNER_SELECTED'
};

// User Roles
const USER_ROLES = {
  BUYER: 'buyer',
  SUPPLIER: 'supplier',
  ADMIN: 'admin'
};

// Notification Types
const NOTIFICATION_TYPE = {
  INFO: 'INFO',
  SUCCESS: 'SUCCESS',
  WARNING: 'WARNING',
  ERROR: 'ERROR'
};

module.exports = {
  RFQ_STATUS,
  TRIGGER_TYPE,
  ACTION_TYPE,
  USER_ROLES,
  NOTIFICATION_TYPE
};
